In [1]:
import pandas as pd

In [25]:
data = {
    'Fecha': ['2024-03-19', '2024-03-20', '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24'],
    'Producto': ['Manzanas', 'Peras', 'Naranjas', 'Plátanos', 'Uvas', 'Melocotones'],
    'Cantidad': [23, 15, 18, 30, 8, 20],
    'Precio': [1.2, 1.5, 1.0, 0.8, 2.0, 1.7]
}

df_ventas = pd.DataFrame(data)
df_ventas

        Fecha     Producto  Cantidad  Precio
0  2024-03-19     Manzanas        23     1.2
1  2024-03-20        Peras        15     1.5
2  2024-03-21     Naranjas        18     1.0
3  2024-03-22     Plátanos        30     0.8
4  2024-03-23         Uvas         8     2.0
5  2024-03-24  Melocotones        20     1.7

In [15]:
def guardar_en_excel(df):
    return df.to_excel('/Users/alejandrobueno/Documents/WWW/cursos,etc/Python/PythonTOTAL_DataScience/ventas1.xlsx', index=False)

In [17]:
guardar_en_excel(df_ventas)

In [27]:
df_ventas['Fecha'] = pd.to_datetime(df_ventas['Fecha'], format="%Y-%m-%d")

In [33]:
df_ventas

       Fecha     Producto  Cantidad  Precio
0 2024-03-19     Manzanas        23     1.2
1 2024-03-20        Peras        15     1.5
2 2024-03-21     Naranjas        18     1.0
3 2024-03-22     Plátanos        30     0.8
4 2024-03-23         Uvas         8     2.0
5 2024-03-24  Melocotones        20     1.7

In [35]:
def guardar_en_excel2(df):
    return df.to_excel('/Users/alejandrobueno/Documents/WWW/cursos,etc/Python/PythonTOTAL_DataScience/ventas2.xlsx', index=False)

guardar_en_excel2(df_ventas)

In [39]:
df_ventas['precio total'] = df_ventas['Cantidad'] * df_ventas['Precio']
df_ventas

       Fecha     Producto  Cantidad  Precio  precio total
0 2024-03-19     Manzanas        23     1.2          27.6
1 2024-03-20        Peras        15     1.5          22.5
2 2024-03-21     Naranjas        18     1.0          18.0
3 2024-03-22     Plátanos        30     0.8          24.0
4 2024-03-23         Uvas         8     2.0          16.0
5 2024-03-24  Melocotones        20     1.7          34.0