In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carmen'],
    'Edad': [25, 30, 22],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia']
}, index=['fila1', 'fila2', 'fila3'])

df

       Nombre  Edad     Ciudad
fila1     Ana    25     Madrid
fila2    Luis    30  Barcelona
fila3  Carmen    22   Valencia

In [21]:
resultado = df.loc[['fila1','fila3']]
resultado

       Nombre  Edad    Ciudad
fila1     Ana    25    Madrid
fila3  Carmen    22  Valencia

In [23]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]
})
df

   A  B   C   D
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16

In [27]:
resultado = df.iloc[[0,1],[2,3]]
resultado

    C   D
0   9  13
1  10  14